// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXLFutLFKzPHwLdd7nlpdzfOBsZUydkw',
    appId: '1:110254435620:web:99151e79522375a9c997b1',
    messagingSenderId: '110254435620',
    projectId: 'el-visionat',
    authDomain: 'el-visionat.firebaseapp.com',
    storageBucket: 'el-visionat.firebasestorage.app',
    measurementId: 'G-H3RP5G8G47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEqhN9-7UrLLrMIcOfUtCXLhqaKMwpm3I',
    appId: '1:110254435620:android:51a114850c418a5dc997b1',
    messagingSenderId: '110254435620',
    projectId: 'el-visionat',
    storageBucket: 'el-visionat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUersbm1jbiXxyEQB-UAO7yWefsdw_UV4',
    appId: '1:110254435620:ios:d2d0a6a82ad64e60c997b1',
    messagingSenderId: '110254435620',
    projectId: 'el-visionat',
    storageBucket: 'el-visionat.firebasestorage.app',
    iosBundleId: 'com.example.elVisionat',
  );
}
